### ISSUE TITLE
Topics/Tags Question

### ISSUE THREAD

**Issue by tyeeman** [mdwhatcott/huguinho#6]
I did create a fork to play around, thanks. Just wondering how to change this - 

```
Topics/tags are only rendered once 3 separate articles reference them
```
I would like Topics/tags to display even if only 1 article references it. Is it a one line update or is it too much? I tried seaching the code and found reference to it but did not see a number like 3 that I could change to 1?

**Comment by mdwhatcott** [comment]
Check out the if statement on line 77 of topic_page_tendering_handler.go. That statement filters out topics that are only used on one article/post. (Looks like a topic need only be used in 2 articles to be included—sorry to mislead.) So, just removing that if statement should do the trick for you (it will also cause a unit test to fail). Admittedly, that filtering logic should be in its own well-named function.

**Comment by tyeeman** [comment]
OK, thanks. I deleted lines 77 to 79 and now I do get a post that has only 1 topic listed under "localhost/topics"...but if I click the link for topic 1 (http://localhost/topics/#topic1), the listing that shows all posts with topic1 and topic2. Is that correct?

**Comment by mdwhatcott** [comment]
The code as you have it is fine.

At one point in the past `huguinho` rendered each topic on a separate page, but I got tired of so many pages (some of which didn't have much on them) so for some time now all topic listings are rendered on the same page:

`/topics/`

Now, most web browsers interpret the [URI Fragment](https://en.wikipedia.org/wiki/URI_fragment) by scrolling to the element with an `id` attribute that matches whatever comes after the `#`.

So, if you're only rendering a few articles and a few topics/tags, the content of the topic listing page will be so short that the browser won't be able to scroll down from the top of the document because it all fits in view. If you add many more articles such that the page grows in size you should see that the browser scrolls to the topic indicated in the URI fragment (`#topic1` in your case). You can see this in action on my own blog:

https://michaelwhatcott.com/topics/#programming

The browser should scroll you to the `programming` list on the `/topics/` page.

**Comment by tyeeman** [comment]
Yes, exactly, I just added more posts/topics and it does what you said so I think it's working fine. Thanks for your help.
